name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Python 3.8 Set-up
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: pip install ipython tqdm requests numpy torch
    - name: Install naivegrad
      run: pip install -e ~/work/naivegrad/naivegrad/
    - name: Run Mnist
      run: ipython3 examples/mnist.py
    - name: Run Other Tests
      run: |
        ipython3 tests/test_core_tn.py
        ipython3 examples/demo/demo_tensor_example.py
