name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Python 3.8 Set-up
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Install naivegrad
      run: pip install -e ~/work/naivegrad/naivegrad/
    - name: Run Pytest
      run: python -m pytest -s -v
